### ISSUE TITLE
Not able to load proBatch package

### ISSUE THREAD

**Issue by Marievlm** [symbioticMe/proBatch#5]
Hi, 

First, thank you so much for the release of your new package proBatch. It seems to be very helpful for the batch correction. 

After loading the necessary packages and execute conscientiously the Rcode from the documentation, I am not able to load the library proBatch. 
In Fact, 
``` 
> library(proBatch)
Erreur : package or namespace load failed for ‘proBatch’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 aucun package nommé ‘GO.db’ n'est trouvé 
```
I try to download from different sources the package "GO.db" -> without success. 

Can you bring me some tips in the way to use your package. 

Thank you so much !

**Comment by ppedrioli** [comment]
Hi Marie,

Sorry for probably confirming the obvious, but did you already try:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GO.db")
```

Also, could you please have a look at the repository for building the docker version of [proBatch](https://github.com/digitalproteomes/docker-probatch). Specifically at the Dockerfile and install_probatch.R and see if any of the dependencies installed there will help you. Note that that image is built on top of [rocker/r-base:4.0.0](https://github.com/rocker-org/rocker/blob/master/r-base/4.0.0/Dockerfile) and I did not test with other R versions. 

Finally, if that does not solve it and you just want to give proBatch a try, you could use the docker image available on [dockerhub](https://hub.docker.com/r/digitalproteomes/probatch).

**Comment by Marievlm** [comment]
Hi Patrick, 

Thank you for your very precise answer and your reactivity. 

Now, it works perfectly !!!
